// Generated by CoffeeScript 1.8.0
(function() {
  var WikiViews, config, fs;

  fs = require('fs');

  WikiViews = require('wikiviews');

  config = require('./config.json');

  if (process.argv.length > 2) {
    config.article = process.argv[2];
  }

  if (process.argv.length > 3) {
    config.filename = process.argv[3];
  }

  WikiViews(config.article, config.start, config.end, function(result) {
    var date, lines, views;
    lines = [];
    for (date in result) {
      views = result[date];
      lines.push("" + date + ", " + views);
    }
    return fs.writeFile(config.filename, lines.join("\n"), function(err) {
      if (err) {
        return console.log(err);
      }
    });
  });

}).call(this);
